version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_started
    environment:
      - DB_SOURCE=root:18032002@tcp(mysql:3306)/todolist?parseTime=true
    networks:
      - todolist_network

  mysql:
    image: mysql:latest
    container_name: mysql_todolist
    environment:
      - MYSQL_ROOT_PASSWORD=18032002
      - MYSQL_DATABASE=todolist
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - todolist_network

volumes:
  mysql_data:

networks:
  todolist_network:
    driver: bridge