// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
)

type TodosPriority string

const (
	TodosPriorityLow    TodosPriority = "low"
	TodosPriorityMedium TodosPriority = "medium"
	TodosPriorityHigh   TodosPriority = "high"
)

func (e *TodosPriority) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TodosPriority(s)
	case string:
		*e = TodosPriority(s)
	default:
		return fmt.Errorf("unsupported scan type for TodosPriority: %T", src)
	}
	return nil
}

type NullTodosPriority struct {
	TodosPriority TodosPriority `json:"todos_priority"`
	Valid         bool          `json:"valid"` // Valid is true if TodosPriority is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTodosPriority) Scan(value interface{}) error {
	if value == nil {
		ns.TodosPriority, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TodosPriority.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTodosPriority) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TodosPriority), nil
}

type Todo struct {
	ID          int32             `json:"id"`
	UserID      int32             `json:"user_id"`
	Title       string            `json:"title"`
	Description sql.NullString    `json:"description"`
	Priority    NullTodosPriority `json:"priority"`
	Deadline    sql.NullTime      `json:"deadline"`
	CreatedAt   sql.NullTime      `json:"created_at"`
	Status      sql.NullBool      `json:"status"`
}

type User struct {
	ID        int32        `json:"id"`
	Username  string       `json:"username"`
	Email     string       `json:"email"`
	Password  string       `json:"password"`
	CreatedAt sql.NullTime `json:"created_at"`
}
