// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateTodo(ctx context.Context, arg CreateTodoParams) (sql.Result, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error)
	DeleteTodo(ctx context.Context, id int32) error
	DeleteTodosByUser(ctx context.Context, userID int32) error
	DeleteUser(ctx context.Context, id int32) error
	DeleteUserTodos(ctx context.Context, userID int32) error
	GetTodo(ctx context.Context, id int32) (Todo, error)
	GetUser(ctx context.Context, id int32) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	ListTodos(ctx context.Context) ([]Todo, error)
	ListTodosByPriority(ctx context.Context, arg ListTodosByPriorityParams) ([]Todo, error)
	ListTodosByStatus(ctx context.Context, arg ListTodosByStatusParams) ([]Todo, error)
	ListTodosByUser(ctx context.Context, userID int32) ([]Todo, error)
	ListUsers(ctx context.Context) ([]User, error)
	UpdateTodo(ctx context.Context, arg UpdateTodoParams) error
	UpdateTodoStatus(ctx context.Context, arg UpdateTodoStatusParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
