# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HomeWork_Buoi13_TranVietAnh' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 5.10'

  # Pods for HomeWork_Buoi13_TranVietAnh

end
